# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.provision "ansible" do |ansible|
        #ansible.verbose = "vvvvv"
        ansible.playbook = "playbook.yml"
        ansible.become = "true"
    end
    config.vm.define "server" do |server|
        server.vm.hostname = "server.loc"
        server.vm.network "private_network", ip: "192.168.11.10"
    end
end